package com.springboot.MyTodoList.telegram.BotSessionManager;

public enum UserStateType {
    START,
    STATE2,
    CREATE_TASK_ENTER_NAME,
    CREATE_TASK_ENTER_DESCRIPTION,
    CREATE_TASK_ENTER_CATEGORY,
    CREATE_TASK_ENTER_TYPE,
    CREATE_TASK_ENTER_PRIORITY,
    ASSIGN_TASK_ENTER_ESTIMATED_HOURS,
    COMPLETE_TASK_ENTER_REAL_HOURS,
    CREATE_SPRINT_ENTER_STARTDATE,
    CREATE_SPRINT_ENTER_ENDDATE
}
