spring:
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}